# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='events_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
