# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170826_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
